#!/bin/bash

# !!! this script is NOT meant to be run inside redux-offline-docs
# but inside a clone of https://github.com/reactjs/redux

target="$HOME/redux-offline-docs"
TODAY=$(date +"%Y-%m-%d")

# delete previous versions
rm $target/redux-documentation-*

# create new versions
formats=(pdf epub mobi)
for format in "${formats[@]}"
do
  gitbook $format . $target/redux-documentation-$TODAY.$format -- log=debug --debug
done
